"""add universal review fields

Revision ID: add_universal_review_fields
Revises: d94164ae02f2
Create Date: 2025-01-03 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1b2c3d4e5f6'
down_revision = 'd94164ae02f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_items', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feedback_items', sa.Column('imported_via', sa.String(), nullable=True))
    op.add_column('feedback_items', sa.Column('original_platform', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_items', 'original_platform')
    op.drop_column('feedback_items', 'imported_via')
    op.drop_column('feedback_items', 'date')
    # ### end Alembic commands ###
